# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    routing_slug_regex: '[a-z0-9]+(?:-[a-z0-9]+)*'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{DataFixtures,Entity,Migrations,Tests}'

    # controllers are imported separately to make sure they
    # have the tag that allows actions to type-hint services
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # ALIASES
    App\Service\Redirect\Resolver\RedirectResolver:
        alias: App\Service\Redirect\Resolver\MultipleRedirectResolver

    # MANUALLY WIREING BECAUSE OF PARAMETERS
    App\Service\Redirect\Resolver\MultipleRedirectResolver:
        arguments:
            $mapping:
                - { path: '/clean-coding/principles', target: 'app_cleancoding_principles'}
                - { path: '/clean-coding/examples', target: 'app_cleancoding_examples'}
                - { path: '/clean-coding', target: 'app_cleancoding_index'}
                - { path: '/blog/posts', target: 'app_blog_search'}
                - { path: '/blog', target: 'app_blog_index'}
                - { path: '/', target: 'app_frontpage_index'}